default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: products_app_development

test:
  <<: *default
  database: products_app_test

production:
  <<: *default
  database: products_app_production
  username: products_app
  password: <%= ENV['PRODUCTS_APP_DATABASE_PASSWORD'] %>
